# Generated by Django 6.1 on 2026-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='profile_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clinic_name',
            field=models.CharField(blank=True, default='Healthcare Center', max_length=255),
        ),
    ]
