# Generated by Django 6.1 on 2026-08-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0002_staffmember_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='advice',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.CharField(blank=True, default='500', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='home_location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulances',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_phone',
            field=models.CharField(blank=True, default='+91 11 2678 9999 / 108', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hospital',
            name='occupied_beds',
            field=models.IntegerField(default=268),
        ),
        migrations.AddField(
            model_name='hospital',
            name='tagline',
            field=models.CharField(blank=True, default='Advanced EHR Medical System', max_length=255),
        ),
        migrations.AddField(
            model_name='labreport',
            name='doctor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='labreport',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='labreport',
            name='findings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labreport',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labreport',
            name='lab_department',
            field=models.CharField(blank=True, default='Pathology', max_length=100),
        ),
        migrations.AddField(
            model_name='labreport',
            name='normal_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labreport',
            name='technician_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labreport',
            name='units',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='advice_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diet_advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='expiry_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='next_follow_up',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='shift_timing',
            field=models.CharField(blank=True, default='09:00 AM - 05:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_diagnosis',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_treatment_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patient_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift_timing',
            field=models.CharField(blank=True, default='09:00 AM - 05:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='treatment_status',
            field=models.CharField(blank=True, default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, default='Plot 42, Medical Enclave, Health City, New Delhi'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='admin_password',
            field=models.CharField(default='admin123', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='admin_username',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, default='director@healthcare.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='Healthcare Center', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, default='+91 11 2678 9000', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_beds',
            field=models.IntegerField(default=350),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_doctors',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_patients',
            field=models.IntegerField(default=1450),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(default='Ready', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='availability',
            field=models.CharField(blank=True, default='Mon - Sat', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='consultation_fee',
            field=models.CharField(blank=True, default='700', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('technician', 'Staff Technician'), ('pharmacy', 'Pharmacy Staff'), ('lab', 'Lab Staff')], default='doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='working_hours',
            field=models.CharField(blank=True, default='8 Hours / Day', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='O+', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clinic_address',
            field=models.TextField(blank=True, default='Plot 42, Medical Enclave, Health City, New Delhi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(blank=True, default='8 Hours / Day', max_length=100),
        ),
    ]
